export var FIELD_TYPES = {
  text:       { icon: 'T',   badge: 'Text Field',    hasOptions: false },
  area:       { icon: '📄',  badge: 'Text Area',     hasOptions: false },
  date:       { icon: '📅',  badge: 'Date',          hasOptions: false },
  radio:      { icon: '⊙',  badge: 'Radio Buttons',  hasOptions: true  },
  check:      { icon: '☑',  badge: 'Checkboxes',     hasOptions: true  },
  select:     { icon: '▾',   badge: 'Dropdown',      hasOptions: true  },
  credential: { icon: '🔑',  badge: 'Credential',    hasOptions: false },
  totp:       { icon: '🔐',  badge: 'TOTP Code',     hasOptions: false },
  filename:   { icon: '📂',  badge: 'Filename',      hasOptions: false },
  dir:        { icon: '🗂',  badge: 'Directory',     hasOptions: false },
  parse:      { icon: '🔍',  badge: 'Parse',         hasOptions: false },
  number:     { icon: '#',   badge: 'Number',        hasOptions: false },
  email:      { icon: '@',   badge: 'Email',         hasOptions: false },
  phone:      { icon: '☎',  badge: 'Phone',          hasOptions: false },
  url:        { icon: '🔗', badge: 'URL',             hasOptions: false },
  datetime:   { icon: '🕐', badge: 'DateTime',       hasOptions: false },
  image:      { icon: '🖼', badge: 'Image',           hasOptions: false, hasSrc: true },
  richtext:   { icon: '✍',  badge: 'Rich Text',      hasOptions: false },
  computed:   { icon: '⚡', badge: 'Computed',       hasOptions: false, hasExpr: true },
  signature:  { icon: '✒',  badge: 'Signature',      hasOptions: false },
  attachment: { icon: '📎', badge: 'Attachment',     hasOptions: false },
};
